services:
  # NestJS приложение
  app:
    build:
      context: .  # Папка с Dockerfile
      dockerfile: Dockerfile  # Имя Dockerfile (проверь, что оно именно так пишется)
    ports:
      - "3001:3000"  # Открываем порт для NestJS
    env_file:
      - .env  # Загружаем переменные окружения
    depends_on:
      - db  # Ждем, пока база поднимется
    restart: always  # Автоматический рестарт при сбое

  # База данных PostgreSQL
  db:
    image: postgres:13.3
    ports:
      - "5433:5432"  # Подключаем порт PostgreSQL
    env_file:
      .env
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1993"
      POSTGRES_DB:  "postgres"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always  # Автоматический рестарт при сбое

volumes:
  db_data:
